spring.application.name=zone-management-service
server.port=8081
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server.servlet.context-path=/zone-management-service

eureka.instance.hostname=